name: Deploy Template

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Cloudformation Template Deploy
      run: |
        ./.integration
      env:
        Name: ${{ secrets.CFN_NAME }}
        Domain: ${{ secrets.ACME_DOMAIN }}
        Email: ${{ secrets.ACME_EMAIL }}
        Bucket: ${{ secrets.S3_BUCKET }}
        PrivKey: ${{ secrets.S3_PRIVKEY }}
        PubKey: ${{ secrets.S3_PUBKEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
